<a href="https://colab.research.google.com/github/simon-clematide/colab-notebooks-for-teaching/blob/main/Pragmatic_Gradients.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Pragmatic Gradients in Pytorch
This notebook shows how practical machine learning "monkey" patches common mathematically undefined gradients

## ReLu
Not smooth at $x= 0$

In [ ]:
import torch

# Define a tensor with a value of 0
x = torch.tensor(0.0, requires_grad=True)

# Apply ReLU
relu_output = torch.relu(x)

# Perform backpropagation
relu_output.backward()

# Output the gradient
print("ReLU Output:", relu_output)  # Should output: tensor(0.)
print("Gradient at x=0:", x.grad)    # Should output: tensor(0.)

ReLU Output: tensor(0., grad_fn=<ReluBackward0>)
Gradient at x=0: tensor(0.)


## maximum function

In [ ]:

# Define two equal tensors
a = torch.tensor(1.0, requires_grad=True)
b = torch.tensor(1.0, requires_grad=True)

# Perform max operation
max_value = torch.max(a, b)

# Backpropagation
max_value.backward()

# Gradients
print(a.grad)  # Output: tensor(1.)
print(b.grad)  # Output: tensor(0.)


tensor(0.5000)
tensor(0.5000)


## abs function

In [1]:

# Define a tensor with zero
x = torch.tensor(0.0, requires_grad=True)

# Compute the absolute value
abs_value = torch.abs(x)

# Backpropagation
abs_value.backward()

# Output the results
print("Absolute Value:", abs_value)          # Outputs: tensor(0.)
print("Gradient:", x.grad)                    # Outputs: tensor(0.)


Absolute Value: tensor(0., grad_fn=<AbsBackward0>)
Gradient: tensor(0.)


## softmax function

In [ ]:
import torch
import torch.nn as nn

# Define equal logits
logits = torch.tensor([1.0, 1.0], requires_grad=True)

# Apply softmax
probabilities = torch.softmax(logits, dim=0)

# Define a target for cross-entropy loss
target = torch.tensor([1])  # Assuming we want the first class

# Compute cross-entropy loss
loss = nn.CrossEntropyLoss()(logits.unsqueeze(0), target)

# Backpropagation
loss.backward()

print("Softmax Output:", probabilities)  # Should show equal probabilities
print("Gradients:", logits.grad)          # Should not be zero


Softmax Output: tensor([0.5000, 0.5000], grad_fn=<SoftmaxBackward0>)
Gradients: tensor([ 0.5000, -0.5000])


## Dot product

In [2]:
a = torch.tensor([1.0, 2.0], requires_grad=True)
b = torch.tensor([3.0, 4.0], requires_grad=True)
dot_product = torch.dot(a, b)
dot_product.backward()

# Gradients
print(a.grad)  # Should give tensor([3.0, 4.0])
print(b.grad)  # Should give tensor([1.0, 2.0])

tensor([3., 4.])
tensor([1., 2.])


## Matrix-Vector Multiplication

In [9]:
A = torch.tensor([[1.0, 2.0], [3.0, 4.0]], requires_grad=True)
x = torch.tensor([5.0, 6.0], requires_grad=True)
z = torch.matmul(A, x)

z.backward(torch.ones_like(z))
print(x.grad)  # Gradients with respect to x

tensor([4., 6.])


## No gradient

In [3]:
x = torch.tensor(3.,requires_grad=False)
y = torch.tensor(4.,requires_grad=True)
f=(x*x)*y+(y+2)

In [4]:
print(f)

tensor(42., grad_fn=<AddBackward0>)


In [5]:
f.backward()

In [6]:
x.grad, y.grad

(None, tensor(10.))