<a href="https://colab.research.google.com/github/simon-clematide/colab-notebooks-for-teaching/blob/main/pytorch_autograd_matrix.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Automatic Differentiation in PyTorch
See Chapter 1 of [RaoMcMahan:2019] for an introduction into torch tensors.
See also https://www.deeplearningwizard.com/deep_learning/practical_pytorch/pytorch_gradients/ for applied introduction.

In [ ]:
import torch

In [ ]:
x = torch.ones(2,2,requires_grad=True)

In [ ]:
x

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)

In [ ]:
print(x.grad)

None


In [ ]:
y = (x+2)*(x+5)+3

In [ ]:
y

tensor([[21., 21.],
        [21., 21.]], grad_fn=<AddBackward0>)

In [ ]:
z = y.mean()

In [ ]:
z

tensor(21., grad_fn=<MeanBackward0>)

In [ ]:
z.backward()

In [ ]:
z

tensor(21., grad_fn=<MeanBackward0>)

In [ ]:
x

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)

In [ ]:
x.grad

tensor([[2.2500, 2.2500],
        [2.2500, 2.2500]])

## Let's minimize z with respect to x a bit
Remember x' = x - learnrate * sign(f'(x))

In [ ]:
x.sign()

tensor([[1., 1.],
        [1., 1.]], grad_fn=<SignBackward0>)

In [ ]:
next_x = x - 0.01*x.sign()*x.grad

In [ ]:
next_x

tensor([[0.9775, 0.9775],
        [0.9775, 0.9775]], grad_fn=<SubBackward0>)